### ISSUE TITLE
Getting Data from Chart as Table

### ISSUE THREAD

**Issue by htmlguy** [pypl/pypl.github.io#1]
How can I get the popularity data from the line graph on the PYPL.html page in a format such as html table, csv, tabulated file, etc?

**Comment by pcarbonn** [comment]
I'm curious : what is your use case ?  What would you use it for ?

**Comment by htmlguy** [comment]
My intent was to perform several calculations on the information over time,
as well as graphing the data again.

**Comment by pcarbonn** [comment]
You can get it in javascript format [here](http://pypl.github.io/PYPL/All.js).  Replace All.js by the country name you want. 
Please provide proper attribution when referring to it. (see [Creative Commons Attribution 3.0 Unported License](http://creativecommons.org/licenses/by/3.0/)

**Comment by benlakey** [comment]
Processing javascript as-is from an untrusted third-party (you) is not a great practice from a security standpoint. It would be better if this data were available as a data dump (csv, json, etc).
