### ISSUE TITLE
Add "RAD Studio" to IDE list

### ISSUE THREAD

**Issue by darianmiller** [pypl/pypl.github.io#14]
RAD Studio is the IDE used by Delphi and C++ Builder from Embarcadero.

It's not listed in the Top 30 IDEs on this page: https://pypl.github.io/IDE.html, even though it's more popular than some listed on this page.  

For example, RAD Studio as compared to Sharp Develop on Google Trends which is listed at #26 on your list:
![image](https://user-images.githubusercontent.com/3165264/107277937-c0b95f00-6a1a-11eb-8fc7-ef034e242937.png)

**Comment by pcarbonn** [comment]
Thanks for the tip.  I plan to include it in the next publication.
