### ISSUE TITLE
Rename "C" to "C/C++"?

### ISSUE THREAD

**Issue by crlf0710** [pypl/pypl.github.io#2]
"C++ has the same popularity as C on Google trends: to avoid duplication, it is not included in the PYPL index." According to this, and to minimize confusion, i think it's more proper to rename "C" to "C/C++".

**Comment by pcarbonn** [comment]
Good idea.  Will do.

**Comment by crlf0710** [comment]
I see it done. Great. And any chance to rename "lua" to properly upper-cased "Lua"?

**Comment by pcarbonn** [comment]
Sure.  Will be done next month. Thanks.

**Comment by crlf0710** [comment]
Thanks, you may close this when it's done.

**Comment by crlf0710** [comment]
Since everything's done. I'm gonna close this.
