### ISSUE TITLE
Go status should be shown as growing ("UpUp")

### ISSUE THREAD

**Issue by fedir** [pypl/pypl.github.io#3]
Hi !
Go should be shown as growing with http://pypl.github.io/Up.png on http://pypl.github.io/PYPL.html.
As the language had + 50% of usage comparing with the last year.
Please fix.
Best regards,
Fedir

**Comment by paulvi** [comment]
It is still growing and is shown as such now.

Should issue be closed?

**Comment by pcarbonn** [comment]
The Up arrow represents a change in ranking, not a change of popularity (share).
